site_name: sbrothers7 Docs
theme: 
  name: modern 
  logo: images/logo.png
  icon:
    edit: material/pencil
    view: material/eye
  favicon: images/favicon.png
  palette: 
    - scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.footer
    - content.action.view
    - navigation.instant

extra:
  generator: false

copyright: "Copyright &copy; 2026 sbrothers7"
site_description: sbrothers7 Documentation
docs_dir: docs
site_dir: site


extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Linux:
    - Arch Linux: Linux/Arch-Linux.md
    - GRUB: Linux/GRUB.md

  - macOS:
    - Emulation Layers: macOS/Emulation-Layers.md
    - UTM Guides: macOS/UTM-Guides.md
    - Virtualization & Emulation: macOS/Virtualization-and-Emulation.md
    - Ricing: macOS/Ricing.md

    - '"Windows Only"':
        - ADOFAI Modding: macOS/"Windows Only"/ADOFAI-Modding.md
        - DJMAX: macOS/"Windows Only"/DJMAX.md

    - Natively Installing Other OSes:
        - Installing Linux: macOS/Natively Installing Other OSes/Installing-Linux.md
        - Installing Windows: macOS/Natively Installing Other OSes/Installing-Windows.md

    - Other:
        - Sikarugir: macOS/Other/Sikarugir.md

  - Windows: 
    - Versions: Windows/Windows-Versions.md
    - Using XP: Windows/Using-XP.md

  - Other:
    - Experiments: 
      - Installing Windows XP on a Modern System: Other/Experiments/Installing-XP.md
    - Hybrid MBR: Other/Hybrid-MBR.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tilde