site_name: sbrothers7 Docs
theme: 
  name: modern 
  logo: images/logo.png
  favicon: images/favicon.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to light mode

site_description: sbrothers7 Documentation

repo_url: https://github.com/sbrothers7/Documentation/
edit_uri: https://github.com/sbrothers7/Documentation/blob/main/docs/

nav:
  - macOS:
    - Emulation Layers: macOS/Emulation-Layers.md
    - UTM Guides: macOS/UTM-Guides.md
    - Virtualization & Emulation: macOS/Virtualization-and-Emulation.md
    - Ricing: macOS/Ricing.md

    - '"Windows Only"':
        - ADOFAI Modding: macOS/"Windows Only"/ADOFAI-Modding.md
        - DJMAX: macOS/"Windows Only"/DJMAX.md

    - Natively Installing Other OSes:
        - Installing Linux: macOS/Natively Installing Other OSes/Installing-Linux.md
        - Installing Windows: macOS/Natively Installing Other OSes/Installing-Windows.md

    - Other:
        - Sikarugir: macOS/Other/Sikarugir.md

  - Windows: 
    - Versions: Windows/Windows-Versions.md
    - Using XP: Windows/Using-XP.md

  - Linux:
    - Arch Linux: Linux/Arch-Linux.md
    - GRUB: Linux/GRUB.md

  - Other:
    - Hybrid MBR: Other/Hybrid-MBR.md

# extra_css:

# extra_javascript:

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tilde